name: flutter_fortune_wheel_example
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_hooks: ^0.20.5
  go_router: ^14.2.0
  flutter_fortune_wheel:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11

flutter:
  uses-material-design: true
